[discrete]
WARNING: This is a work in progress and is not yet to be used. See
https://owletcare.atlassian.net/browse/COREE-156[COREE-156].

= Developing RESTful APIs: A Comprehensive Set of Guidelines by Owlet

image:https://g.codefresh.io/api/badges/pipeline/owletcare/Core%20Experience%2Fasciidoc?type=cf-2&key=eyJhbGciOiJIUzI1NiJ9.NWRmYjlkZDZjNmRiMTFiYzBmZGQ3MTY4.2NXb5d_4_lo7zKa24tq93M2-YHazikKUW0TDdzUas2c["Codefresh build status", link="https://g.codefresh.io/pipelines/edit/new/builds?id=60afd8aaa2cbf6f9eba85572&pipeline=asciidoc&projects=Core%20Experience&projectId=5dfd46bb6baea5cfb6de77c4"]

== Purpose

Great RESTful APIs look like they were designed by a single team. This
promotes API adoption, reduces friction, and enables clients to use them
properly. To build APIs that meet this standard, and to answer many
common questions encountered along the way of RESTful API development,
the Owlet team has created this set of guidelines.

== Usage

Feel free to use these guidelines as a guidance for your own
development. Note that we encourage our own teams to use them in order
to challenge their APIs. As such, you should consider this to be a
living, evolving document. We will revise and update based on our
learnings and experiences.

See link:BUILD.adoc[BUILD documentation] for technical details.

=== Prerequesites

In order to use AsciiDoc, which is what the styleguide is written in, there are
a few requirements that need to be met.

1. https://www.ruby-lang.org/en/documentation/installation/#ruby-install[Install Ruby]

2. Install Asciidoctor

    sudo gem install asciidoctor -v 2.0.15

3. Install coderay

    sudo gem install coderay

4. Install asciidoctor-pdf

    sudo gem install asciidoctor-pdf

5. Install asciidoctor-epub3

    sudo gem install asciidoctor-epub3

=== Running Locally

Clone the repo and go to project directory

----
git clone https://github.com/OwletCare/api-style-guide.git

cd api-style-guide
----

Use commands in link:Makefile[Makefile]

NOTE: There are a few known errors that happen when building the documents. If
you get any more errors than those below, something is wrong. The separate errors
are also all included in the `make all` command.

....
make pdf

asciidoctor-pdf -D output index.adoc;
asciidoctor: ERROR: failed to parse formatted text: <span class="should-keyword">&#x26a0;&#xFE0F;</span> No, but <a anchor="229"><span class="should-keyword">SHOULD</span> consider to design <code>POST</code> and <code>PATCH</code> idempotent</a>
asciidoctor: ERROR: failed to parse formatted text: <span class="should-keyword">&#x26a0;&#xFE0F;</span> May, but only if specific <a href="#post"><code>POST</code></a> endpoint is <a anchor="safe">safe</a>. <strong>Hint:</strong> not supported by most caches.
asciidoctor: ERROR: failed to parse formatted text: <span class="should-keyword">&#x26a0;&#xFE0F;</span> No, but <a anchor="229"><span class="should-keyword">SHOULD</span> consider to design <code>POST</code> and <code>PATCH</code> idempotent</a>
asciidoctor: ERROR: failed to parse formatted text: <span class="should-keyword">&#x26a0;&#xFE0F;</span> No, but <a anchor="229"><span class="should-keyword">SHOULD</span> consider to design <code>POST</code> and <code>PATCH</code> idempotent</a>
asciidoctor: ERROR: failed to parse formatted text: <span class="should-keyword">&#x26a0;&#xFE0F;</span> May, but only if specific <a href="#post"><code>POST</code></a> endpoint is <a anchor="safe">safe</a>. <strong>Hint:</strong> not supported by most caches.
asciidoctor: ERROR: failed to parse formatted text: <span class="should-keyword">&#x26a0;&#xFE0F;</span> No, but <a anchor="229"><span class="should-keyword">SHOULD</span> consider to design <code>POST</code> and <code>PATCH</code> idempotent</a>
....

....
make epub

asciidoctor-epub3 --failure-level=ERROR -D output index.adoc;
asciidoctor: WARNING: index.adoc: invalid reference to unknown anchor: required-nullable-row-2
....

== License

We have published these guidelines under the CC-BY (Creative commons
Attribution 4.0) license. Please see link:LICENSE[LICENSE file].

== Attributions

link:ATTRIBUTION.adoc[Attributions]
