[[general-guidelines]]
= General guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.


[#100]
== {MUST} follow API first principle

You must follow the <<api-first, API First Principle>>, more specifically:

* You must define APIs first, before coding its implementation, <<101, using
  OpenAPI as specification language>>
* You must call for early review feedback from peers and client developers
  for all component external APIs, i.e. all apis
  with `x-api-audience =/= component-internal` (see <<219>>).


[#101]
== {MUST} provide API specification using OpenAPI

We use the http://swagger.io/specification/[OpenAPI specification] as standard
to define API specification files. API designers are required to provide the API
specification using a single *self-contained YAML* file to improve readability.

We only support *OpenAPI 3.0*, and do not support *OpenAPI 2.0* (a.k.a. Swagger 2).

The API specification files should be subject to version control using a source
code management system - best together with the implementing sources.

You <<192, must>> the component
API specification with the deployment of the implementing service, and, hence,
make it discoverable.

[#102]
== {SHOULD} provide API user manual

In addition to the API Specification, it is good practice to provide an API
user manual to improve client developer experience, especially of engineers
that are less experienced in using this API. A helpful API user manual
typically describes the following API aspects:

* API scope, purpose, and use cases
* concrete examples of API usage
* edge cases, error situation details, and repair hints
* architecture context and major dependencies - including figures and
sequence flows

The user manual should be published online, e.g. via a documentation hosting
platform service, GHE pages, or specific team web servers.

[#234]
== {MUST} not use remote references

API specification files must be *self-contained*, i.e. files
should not contain references to remote content, e.g.
`$ref: 'https://owletcare.github.io/api-style-guide/money-1.0.0.yaml'`.
The reason is, that the content referred to is _in general_ *not durable* and
*not immutable*. As a consequence, the semantic of an API may change in
unexpected ways.

You should, however, use local references to resources when the resource
that is referenced:

* Goes through a visible review process that requires other developers to verify changes.
* Is defined as a re-usable API fragment.

Because these references are controlled, we can ensure that their content is *durable* and
*immutable*.