[[introduction]]
= Introduction

API's following this guide provide functionality via RESTful APIs with a JSON
payload. Engineering teams own, deploy and operate these microservices. APIs
most express what our systems do. API's are to be designed with
high-quality and a long-lasting mindset.

"API First" is a key
engineering principle in regards to API's. Microservice development begins with
API's
defined outside the code and involves peer-review
feedback to achieve high-quality APIs. API First encompasses a set of
quality-related standards and fosters a peer review culture including a
lightweight review procedure. When done this way API's are:

* Easy to understand and learn
* General and abstracted from specific implementation and use cases
* Robust and easy to use
* Have a common look and feel
* Follow consistent RESTful style and syntax
* Consistent with other teams’ APIs and global architecture

Ideally, APIs will look like the same author created them.


[[conventions-used-in-these-guidelines]]
== Conventions used in these guidelines

The requirement level keywords "MUST", "MUST NOT", "SHOULD", "SHOULD NOT", "MAY"
used in this document (case insensitive) are to be
interpreted as described in https://www.ietf.org/rfc/rfc2119.txt[RFC
2119].
