[[security]]
= REST Basics - Security


[#104]
== {MUST} secure endpoints

Every API endpoint must be protected and armed with authentication and authorization.
As part of the API definition you must specify how you protect your API using the
security schemes defined in the
https://swagger.io/docs/specification/authentication/[OpenAPI Authentication Specification].

The majority of our APIs are protected via API Key, JWT Token, Basic Auth,
or Certificate Auth.
The following code snippet shows how to define the bearer security scheme.

[source,yaml]
----
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
----

The bearer security schema can then be applied to all API endpoints.

In other, more specific situations e.g. with customer and partner facing APIs you
may use other OAuth 2.0 authorization flows as defined by {RFC-6749}[RFC 6749].
Please consult the
https://swagger.io/docs/specification/authentication/oauth2/[OpenAPI OAuth 2.0 Authentication]
section for details on how to define `oauth2` typed security schemes correctly.

*Note:* Do not use OpenAPI `oauth2` typed security scheme flows (e.g. `implicit`)
if your service does not fully support it and implements a simple bearer token scheme,
because it exposes authentication server address details and may make use of redirection.


[#105]
== {MAY} define and assign permissions (scopes)

APIs may define permissions to protect their resources. Thus, at least one
permission may be assigned to each API endpoint.

The naming schema for permissions corresponds to the naming schema for <<224,
hostnames>> and <<213, event type names>>. Please refer to <<225>> for
designing permission names and see the following examples.

[cols="25%,20%,15%,40%",options="header",]
|=======================================================================
| Application ID | Resource ID | Access Type | Example
| `order-management` | `sales-order` | `read` | `order-management.sales-order.read`
| `order-management` | `shipment-order` | `read` | `order-management.shipment-order.read`
| `fulfillment-order` | | `write` | `fulfillment-order.write`
| `business-partner-service` | |`read` | `business-partner-service.read`
|=======================================================================

////
//Prepared change for functional permission names:

[cols="15%,15%,15%,15%,40%",options="header",]
|=======================================================================
| Domain | Component | Resource | Access Type | Example
| finance | exchange-rate | - | write | z::finance.exchange-rate.write
| transactions | order | - | read | z::transactions.order.read
| customer | address | shipment-address | read  | z::customer.address.shipment-address.read
|=======================================================================
[cols="30%,15%,15%,40%",options="header",]
|=======================================================================
| Application | Resource | Access Type | Example
| business-partner-service | | - | read | z::business-partner-service.read
| order-management | sales-order | write | z::order-management.sales-order.write
|=======================================================================

////

*Note:* APIs should stick to component specific permissions without resource
extension to avoid the complexity of too many fine-grained permissions. For the
majority of use cases, restricting access for specific API endpoints using read
or write is sufficient.

The defined permissions are then assigned to each API endpoint based on the
security schema by specifying the
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#securityRequirementObject[security requirement]
as follows:

[source,yaml]
----
paths:
 /business-partners/{partner-id}:
    get:
      summary: Retrieves information about a business partner
      security:
        - BearerAuth: [ business-partner-service.read ]
----


[#225]
== {MUST} follow naming convention for permissions (scopes)

If <<105,defining and assigning permissions>>, permission names in APIs must conform to the following naming pattern:

[source,bnf]
-----
<permission> ::= <standard-permission> |  -- should be sufficient for majority of use cases
                 <resource-permission> |  -- for special security access differentiation use cases
                 <pseudo-permission>      -- used to explicitly indicate that access is not restricted

<standard-permission> ::= <application-id>.<access-mode>
<resource-permission> ::= <application-id>.<resource-name>.<access-mode>
<pseudo-permission>   ::= uid

<application-id>      ::= [a-z][a-z0-9-]*  -- application identifier
<resource-name>       ::= [a-z][a-z0-9-]*  -- free resource identifier
<access-mode>         ::= read | write    -- might be extended in future
-----

This pattern is compatible with the previous definition.

////
//Prepared change for functional permission names:
Permission names in APIs must, respectively should conform to the functional
naming depending on the <<219, audience>> as follows (see <<223>> for details
and `<functional-name>` definition):

[source,bnf]
-----
<permission> ::= <functional-permission> |
                 <standard-permission> |  -- standard permission without functional naming
                 <resource-permission> |  -- resource permission without functional naming
                 <pseudo-permission>      -- used to indicate unrestricted access

<functional-permission> ::= z::<functional-name>[.<resource-name>].<access-mode>
<pseudo-permission>     ::= uid

<resource-name>       ::= [a-z][a-z0-9-]*  -- free resource identifier
<access-mode>         ::= read || write    -- might be extended in future
-----

The following application specific legacy convention is *only* allowed for
permissions names of <<223, internal>> APIs:

[source,bnf]
-----
<standard-permission> ::= <application-id>.<access-mode>
<resource-permission> ::= <application-id>.<resource-name>.<access-mode>

<application-id>      ::= [a-z][a-z0-9-]*  -- application identifier

-----

////
