[[security]]
= REST Basics - Security


[#104]
== {MUST} secure endpoints

Every API endpoint must be protected and armed with authentication and authorization.
As part of the API definition you must specify how you protect your API using the
security schemes defined in the
https://swagger.io/docs/specification/authentication/[OpenAPI Authentication Specification].

The majority of our APIs are protected via API Key, JWT Token, Basic Auth,
or Certificate Auth.
The following code snippet shows how to define the bearer security scheme.

[source,yaml]
----
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
----

The bearer security schema can than be applied to all API endpoints.

In other, more specific situations e.g. with customer and partner facing APIs you
may use other OAuth 2.0 authorization flows as defined by {RFC-6749}[RFC 6749].
Please consult the
https://swagger.io/docs/specification/authentication/oauth2/[OpenAPI OAuth 2.0 Authentication]
section for details on how to define `oauth2` typed security schemes correctly.

*Note:* Do not use OpenAPI `oauth2` typed security scheme flows (e.g. `implicit`)
if your service does not fully support it and implements a simple bearer token scheme,
because it exposes authentication server address details and may make use of redirection.